<?xml version="1.0" encoding="utf-8"?>
<Database Name="TMDT_DB" EntityNamespace="DBO.DATA" ContextNamespace="DBO.DATA" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Exam" Member="Exam">
    <Type Name="Exam">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
</Database>